title: Otavio Manzano Kavakama
author: omk
email: otaviokavakama@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Otavio Manzano Kavakama is a cellist, and that's pretty much all.

# social links
twitter_username: kavotaman # DO NOT include the @ character, or else the build will fail!
github_username:  kavotaman # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
